global_experiment_manager:
  ros__parameters:
    use_sim: false

    # --- Active Hardware Definitions ---
    active_camera_aligner: end_effector_comply
    active_target_platform: target_platform
    marker_configuration: noncoplanar   # Options: coplanar, noncoplanar
    tool_placement: perpendicular  # Options: parallel, perpendicular (relative to whiteboard platform) 
    number_of_markers: 5

    # Frame Definitions
    task_frame: whiteboard
    base_frame: elfin_base_link
    
    # --- Canvas / Workspace Boundaries ---
    canvas_width: 0.30   # 30 cm wide
    canvas_height: 0.20  # 20 cm tall
    
    # --- Trajectory Parameters ---
    drawing_feedrate: 0.05       # Meters per second
    plunge_feedrate: 0.05        # Slower speed for lifting/plunging the pen
    z_plunge_depth: 0.0025
    z_lift_height: 0.025
    z_hover_height: 0.050

    # --- Control Loop Parameters ---
    control_loop_rate: 100.0    # 100 Hz control loop
    controller_type: mpc     # Options: pid, pid_ff, mpc
    filter_type: kalman_filter  # Options: raw, ema_filter, kalman_filter